
lista_siglas = {
'ABS': 'Anti-Lock Braking System' ,
'ACR': 'Automatic Compression Release' ,
'AFR': 'Air Fuel Ratio' ,
'AIS': 'Active Intake Solenoid' ,
'ATS': 'Air Temperature Sensor' ,
'BAS': 'Bank Angle Sensor' ,
'BCM': 'Body Control Module' ,
'CAN': 'Controller Area Network' ,
'CCM': 'Cruise Control Module' ,
'CKP': 'Crank Position Sensor' ,
'DLC': 'Datalink Connector' ,
'DTC': 'Diagnostic Trouble Codes' ,
'ECM': 'Electronic Control Module' ,
'ECT': 'Engine Coolant Temperature' ,
'ECU': 'Electronic Control Unit' ,
'EFI': 'Electronic Fuel Injection' ,
'EFP': 'Electronic Fuel Pump' ,
'ET': 'Engine Temperature sensor' ,
'FUI': 'Fuel Injectors' ,
'FPR': 'Fuel Pressure Regulator' ,
'H-DSSS': 'Harley-Davidson® Smart Security System' ,
'HCU': 'Hydraulic Control Unit, ABS' ,
'HFSM': 'Hands Free Security Module' ,
'HO2S': 'Heated Oxygen Sensor' ,
'IAC': 'Idle Air Control actuator' ,
'IAT': 'Intake Air Temperature sensor' ,
'ICM': 'Ignition Control Module' ,
'IMAP': 'MAP + IAT in one unit' ,
'ISS': 'Ion Sensing System' ,
'JSS': 'Jiffy Stand Sensor' ,
'LHCM': 'Left Hand Control Module' ,
'RHCM': 'Right Hand Control Module' ,
'MAP': 'Manifold Absolute Pressure sensor' ,
'MHR': 'Right Hand Control Module' ,
'RCM': 'Reverse Control Module' ,
'SPEEDO': 'Speedometer' ,
'TCA': 'Throttle Control Actuator' ,
'TGS': 'Twist Grip Sensor' ,
'TMAP': 'Intake Air Temperature / Manifold Absolute Pressure equipment' ,
'TPS': 'Throttle Position Sensor' ,
'TSM / TSSM': 'Turn Signal / Turn Signal Security Module)' ,
'VE': 'Volume Efficiency' ,
'VIN': 'Vehicle Identification Number' ,
'VSS': 'Vehicle Speed ​​Sensor' ,
'WSS': 'Wheel Speed ​​Sensor'
}
